version: 0.1.{build}
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- ps: nuget restore
build:
  verbosity: minimal
after_build:
- ps: .\nuget\pack.ps1
test: off
artifacts:
- path: '**\*.nupkg'
- path: '**\*.dll'
deploy:
- provider: NuGet
  api_key:
    secure: M5xjSruqg/MfDfZlWhBj64aknsRPm+rIlGLnztLgqUrC4DZ0brdtNvUkEoNxrb57
  artifact: /.*\.nupkg/